language: r
sudo: false
cache: 
  packages: true
  pip: true

branches:
    only:
        - gh-pages

env:
  global:
    - ENCRYPTION_LABEL: "4a432f919f81"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - gfortran-4.9
      - libgmp-dev
      - libgsl0-dev
      - pandoc

before_install:
  - mkdir $HOME/bin
  - export PATH=$HOME/bin:$PATH
  - echo $LD_LIBRARY_PATH
  - echo $LIBRARY_PATH

install:
  - pip install --user mkdocs
  - pip install --user python-markdown-math
  - Rscript .utility/r_packs_install.R

script:
  - ./build

after_success:
  - bash .utility/push-tutorial-to-gh-pages.sh

notifications:
  email:
    recipients:
        - bernd_bischl@gmx.net
        - code@jakob-r.de
    on_success: change
    on_failure: always